### ISSUE TITLE
Setup doc should include manual setup of "products-db"

### ISSUE THREAD

**Issue by pbernet** [polster/spring-kotlin-handson#1]
Thx. for this nice example and the provided setup.
Everything is running locally. However, I had to create the `products-db` manually via Mongo-Express, before I was able to run `make docker-infra-provision-mongodb`
Maybe that could be included in the setup doc.

**Comment by polster** [comment]
Hey @pbernet - Nothing to thank for, always a pleasure 😄 

Resp. THX for pointing this out, just updated the README: https://github.com/polster/spring-kotlin-handson/commit/fbb33a93c8410e63c31af902e768a12181394f67
